GROQ_API_KEY="" 
[supabase]
SUPABASE_URL="https://vkrvgmhweyrvlexkmrui.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrcnZnbWh3ZXlydmxleGttcnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU1MDE3MjYsImV4cCI6MjEwMTA3NzcyNn0.nvhR3w5FP37n72g-YxOrGF1Rlmv-jsQuoHxI7Z88ET8"
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrcnZnbWh3ZXlydmxleGttcnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU1MDE3MjYsImV4cCI6MjEwMTA3NzcyNn0.nvhR3w5FP37n72g-YxOrGF1Rlmv-jsQuoHxI7Z88ET8"
[google_oauth]
AUTH_REDIRECT_URL="http://localhost:8501"
client_id=""
client_secret=""
[backend]
url="http://localhost:8000"